name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug DNS
        run: echo ${{ secrets.HOST }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: gh-deploy
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ./
          target: /var/www/valentindsj.com/html
